# Final Data Merging: Sentiment and Returns
This script merges stock return data with sentiment results for the test set based on ticker and date -> Data preparation for the final result evaluation!

In [ ]:
import numpy as np
import pandas as pd

In [2]:
df_sentiment = pd.read_csv("sentiments_group 6.csv")
df_sentiment

,Hash,sentiment,date,Ticker,title,content,date_day
0,417780_a1b09e18286c3e77582f10e07b3dd1cf2386572...,1,2024-07-01 00:00:00+00:00,BDX,Boing! 7 Undervalued Stocks That Could Surpris...,The market previously supported a higher multi...,2024-07-01
1,574051_516beded712088f61296c8635a4c0bb31f76ac4...,1,2024-07-01 00:00:00+00:00,CELH,"\nJon Quast | Jul 1, 2024\n",This could be an opportunity.,2024-07-01
2,941051_1d4c383bc62a7761f1ca432c42a84ae63696ae0...,1,2024-07-01 00:00:00+00:00,EME,The 3 Most Promising Stocks Worth Gambling On ...,Not all companies are worth taking the gamble ...,2024-07-01
3,1139270_17cdbeecb5584520d264b537e29c431d3b936f...,1,2024-07-01 00:00:00+00:00,GM,Vroom! 3 EV Stocks With the Potential to Outru...,Although Rivian should be the beneficiary of i...,2024-07-01
4,1209842_3eb959694fc347fa7751d02d234e3e4eaee778...,1,2024-07-01 00:00:00+00:00,HAL,Black Gold Bargains: 7 Discounted Oil Stocks R...,With the world continuing to depend on hydroca...,2024-07-01
...,...,...,...,...,...,...,...
59495,586146_4244a95340713425a33e5abb07c600ae3f7c197...,1,2024-07-26 14:26:00+00:00,PFE,"Pharma Stock Roundup: AZN, SNY, ABBV Q2 Earnin...",Second-quarter earnings releases picked up for...,2024-07-26
59496,1307797_74215fe50a22eeda1d04d1699c6460cbc04049...,1,2024-07-26 14:27:04+00:00,WDAY,"Workday, Inc. (WDAY): Do Street Analysts Recom...",We recently compiled a list of the 10 Best Inf...,2024-07-26
59497,1013113_31e3bcd33830f2ea473005cf0cbf9911af9751...,1,2024-07-26 14:30:00+00:00,TEAM,Atlassian (TEAM) to Report Q4 Earnings: What's...,Atlassian TEAM is scheduled to report fourth-q...,2024-07-26
59498,941020_8f05558d998d683e1cb81f9bc01ee9e6a3dafbb...,-1,2024-07-26 14:35:00+00:00,EME,EMCOR (EME) Q2 Earnings &amp; Revenues Beat Es...,"EMCOR Group, Inc. EME reported impressive seco...",2024-07-26
59499,758883_016387697597783f2e9a67797cc1cc0fc5e63ac...,1,2024-07-26 14:36:00+00:00,CTSH,CommVault (CVLT) to Report Q1 Earnings: What's...,CommVault Systems CVLT is set to report first-...,2024-07-26

In [3]:
df_sentiment['date_day'] = pd.to_datetime(df_sentiment['date_day'])
df_sentiment = df_sentiment.sort_values(by='date_day')
df_sentiment

,Hash,sentiment,date,Ticker,title,content,date_day
0,417780_a1b09e18286c3e77582f10e07b3dd1cf2386572...,1,2024-07-01 00:00:00+00:00,BDX,Boing! 7 Undervalued Stocks That Could Surpris...,The market previously supported a higher multi...,2024-07-01
11282,1098519_ae3307c6b08a67e3ce468d2c24a337c792fd5b...,-1,2024-07-01 15:31:00+00:00,GATX,Here's Why You Should Give Landstar (LSTR) Sto...,"Landstar System, Inc. (LSTR) is currently mire...",2024-07-01
11281,1360869_90e89a5b68e5b6101e2f04bd7b9270b65070ef...,-1,2024-07-01 15:25:00+00:00,IP,Form 8.3 - INTERNATIONAL PAPER CO,"LONDON, July 01, 2024--(BUSINESS WIRE)--\n\nFO...",2024-07-01
11280,400456_fa12a0969792a9ec4326a26c37382c4e9c3fa87...,1,2024-07-01 15:20:00+00:00,NTRS,Northern Trust Releases Sustainability Report,"CHICAGO, July 01, 2024--(BUSINESS WIRE)--North...",2024-07-01
11279,30586_9c2d8d6f0f322850549d15f909cd499b4fbf7392...,1,2024-07-01 15:13:28+00:00,LLY,Sanofi Nears Decision on $1.6B Upgrade For Fra...,Sanofi Nears Decision on $1.6B Upgrade For Fra...,2024-07-01
...,...,...,...,...,...,...,...
54917,339496_d09fda40f7adf41575d75515344d33f88a40604...,-1,2024-12-31 10:44:32+00:00,NET,India's April-Nov fiscal deficit at 52.5% of f...,India's fiscal deficit for April-November was ...,2024-12-31
54918,1333816_2855f7ecb787567950a860d41ec0d17d76b8f4...,-1,2024-12-31 10:45:42+00:00,WLK,Those who invested in Westlake (NYSE:WLK) five...,It hasn't been the best quarter for Westlake C...,2024-12-31
54919,710368_f90c8490d33d125d79799b8b0dadeef9749b6b7...,-1,2024-12-31 10:49:00+00:00,CR,New Strong Sell Stocks for December 31st,Here are three stocks added to the Zacks Rank ...,2024-12-31
54953,1198345_6306bc01a68d7b6f2bef09cdbac278e68666e9...,-1,2024-12-31 12:30:00+00:00,GTES,Amcor Liquidates its 50% Stake in BCNA JV for ...,Amcor AMCR has sold its 50% stake in Bericap N...,2024-12-31
55081,913178_bb6e7c6063310639fe5efa746d2d976a6d6da33...,-1,2024-12-31 19:21:47+00:00,SO,Browns undecided about QB heading into finale ...,The revolving door at quarterback for the Clev...,2024-12-31

In [4]:
df_sentiment["sentiment"].value_counts()

sentiment
 1    36184
-1    23240
 0       76
Name: count, dtype: int64

In [5]:
df_return = pd.read_csv("train_return_data_daily.csv")
df_return

,date,TICKER,PRC,RET,SHROUT,MV_USD,MV_USD_lag
0,1990-03-02,IROQ,-7.625,0.051724,941.0,7.175125e+03,NaN
1,1990-03-05,IROQ,7.250,-0.049180,941.0,6.822250e+03,7.175125e+03
2,1990-03-06,IROQ,7.250,0.000000,941.0,6.822250e+03,6.822250e+03
3,1990-03-07,IROQ,7.500,0.034483,941.0,7.057500e+03,6.822250e+03
4,1990-03-08,IROQ,7.500,0.000000,941.0,7.057500e+03,7.057500e+03
...,...,...,...,...,...,...,...
21828561,2024-12-24,TSLA,462.280,0.073572,3210060.0,1.483947e+09,1.382252e+09
21828562,2024-12-26,TSLA,454.130,-0.017630,3210060.0,1.457785e+09,1.483947e+09
21828563,2024-12-27,TSLA,431.660,-0.049479,3210060.0,1.385654e+09,1.457785e+09
21828564,2024-12-30,TSLA,417.410,-0.033012,3210060.0,1.339911e+09,1.385654e+09
21828565,2024-12-31,TSLA,403.840,-0.032510,3210060.0,1.296351e+09,1.339911e+09

In [ ]:
# sentiment
df_sentiment['date_day'] = pd.to_datetime(df_sentiment['date_day'])
df_sentiment['Ticker'] = df_sentiment['Ticker'].str.upper()

# return
df_return['date'] = pd.to_datetime(df_return['date'])
df_return['TICKER'] = df_return['TICKER'].str.upper()

In [7]:
df_sent_daily = (
    df_sentiment
    .groupby(['Ticker', 'date_day'], as_index=False)
    .agg(sentiment_daily=('sentiment', 'mean'))
)

In [10]:
df_merged = (
    df_return
    .merge(
        df_sent_daily,
        left_on=['TICKER', 'date'],
        right_on=['Ticker', 'date_day'],
        how='right'
    )
)

In [11]:
df_merged['sentiment_daily'] = df_merged['sentiment_daily'].fillna(0)
df_merged

,date,TICKER,PRC,RET,SHROUT,MV_USD,MV_USD_lag,Ticker,date_day,sentiment_daily
0,2024-07-01,A,127.40000,-0.017203,291761.0,3.717035e+07,3.782098e+07,A,2024-07-01,1.0
1,2024-07-16,A,136.06000,0.038547,291761.0,3.969700e+07,3.822361e+07,A,2024-07-16,-1.0
2,2024-07-19,A,131.78000,-0.001440,291761.0,3.844826e+07,3.850370e+07,A,2024-07-19,-1.0
3,2024-07-22,A,133.42000,0.012445,291761.0,3.892675e+07,3.844826e+07,A,2024-07-22,1.0
4,2024-07-23,A,130.64999,-0.020762,291761.0,3.811857e+07,3.892675e+07,A,2024-07-23,-1.0
...,...,...,...,...,...,...,...,...,...,...
59771,2024-12-03,ZWS,40.32000,0.000993,169714.0,6.842868e+06,6.836080e+06,ZWS,2024-12-03,1.0
59772,2024-12-04,ZWS,40.77000,0.011161,169714.0,6.919240e+06,6.842868e+06,ZWS,2024-12-04,1.0
59773,2024-12-12,ZWS,40.01000,-0.008672,169714.0,6.790257e+06,6.849657e+06,ZWS,2024-12-12,1.0
59774,2024-12-13,ZWS,39.77000,-0.005998,169714.0,6.749526e+06,6.790257e+06,ZWS,2024-12-13,1.0
59775,2024-12-24,ZWS,37.82000,0.009072,169714.0,6.418583e+06,6.360881e+06,ZWS,2024-12-24,1.0

In [12]:
df_merged["sentiment_daily"].value_counts()

sentiment_daily
 1.0    36347
-1.0    23353
 0.0       76
Name: count, dtype: int64

In [13]:
df_merged.to_csv("daily_sentiment_return.csv", index=False)